"""Acceptance scenario declarations (see AGENTS.md for the policy they enforce).

Policy: behaviour end-to-end over real archives. No mocks, no fakes, no
synthesised DEX. Ground truth is either the DEX bytecode (bench/disas.py) or
the Python reference implementation -- never rasc's own output. A scenario is
declared here before the code that satisfies it is written.
"""

VERSION = 1

CORPORA = {
    "wechat": {
        "path": "/tmp/rasc_corpus/com.tencent.mm/base.apk",
        "sha256": "ec7ff6d8cee2f5ae684c3e02a16f5b4b528d10d5aa3ca0bc7ffa503240ff922c",
        "kind": "apk",
        "dex_entries": 16,
        "classes": 227802,
        "provenance": "com.tencent.mm base.apk; corpora live under /tmp/rasc_corpus/, they are not part of the repo",
    },
    "settings": {
        "path": "/tmp/rasc_corpus/com.android.settings/base.apk",
        "sha256": "e6777c26b5f271dc7065766d158f51574c6b94c960c6631706a788b2d936426d",
        "kind": "apk",
        "dex_entries": 13,
        "classes": 57535,
        "provenance": "com.android.settings APK",
    },
    "framework": {
        "path": "/tmp/rasc_corpus/framework.jar",
        "sha256": "9e8437ed79e99c5893a968b575520a84001d30631b0d9a00dae257cc2cc7e7d7",
        "kind": "jar",
        "dex_entries": 6,
        "classes": 37815,
        "provenance": "vivo V2324A /system/framework/framework.jar (49.5 MiB, 6 DEX entries)",
    },
}

SCENARIOS = [
    {
        "id": "guards-no-lost-bodies",
        "title": "a short-circuit guard chain keeps every branch body (|| / && must not lose code)",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "settings",
        "class": "Landroidx/core/app/AppLaunchChecker;",
        "expect": {"missing_literals": 0, "missing_methods": 0, "empty_control": 0, "stub": 0},
        "require_stdout_regex": ["android\\.intent\\.category\\.LEANBACK_LAUNCHER", "apply\\(\\)"],
        "note": "ground truth: reference + bytecode (hasCategory(LAUNCHER) and hasCategory(LEANBACK_LAUNCHER) each guarded by if-eqz, both calling apply()). Before fork 5f1873b the else branch rendered as `if (v3_13) { }` -- the second apply() was gone. rasc may express the chain as nested ifs instead of one `||`: semantics, not shape, is what this scenario pins. The pinned androidx.core class is bundled by the settings APK; the original fixture.apk corpus retired when the corpora moved to /tmp/rasc_corpus/.",
    },
    {
        "id": "range-invoke-args",
        "title": "invoke-*/range arguments beyond five registers survive (re-pin pending)",
        "kind": "not-implemented",
        "status": "not-implemented",
        "corpus": "framework",
        "acceptance_criteria": [
            "pin a class on one of the three pinned corpora whose bytecode contains an invoke-*/range call with a string-literal argument beyond register five (ground truth: bench/disas.py instruction dump)",
            "getclass on that class shows every argument, including the literal; expect missing_literals 0 and a require_stdout_regex on the call",
        ],
        "note": "the original pin (Lcom/android/server/accessibility/AccessibilityManagerService;, trailing \"\" argument) lived in services.jar and retired with that corpus. Until a replacement is pinned, >5-register invoke-range decoding stays covered implicitly by ctor-invocation-pairing: its require regex is a seven-argument invoke-direct/range call (classes.dex, wechat), which fails to match if decode truncates the register list at five.",
    },
    {
        "id": "enum-fallback-consistent",
        "title": "an enum whose $VALUES is inlined still renders a coherent class",
        "kind": "class-shape",
        "status": "pass",
        "corpus": "settings",
        "class": "Lcom/google/protobuf/Syntax;",
        "require_stdout_regex": [
            "private Syntax\\(String v1, int v2, int v3\\)",
            "super\\(v1, v2\\);",
            "public static Syntax valueOf\\(String ",
            "public static Syntax\\[\\] values\\(\\)",
            "new com\\.google\\.protobuf\\.Syntax\\(\"SYNTAX_PROTO2\", ",
        ],
        "forbid_stdout_regex": ["Syntax\\(\\)\\s*\\{"],
        "note": "ground truth: bytecode (the constructor takes (String name, int ordinal, int value) and calls super(name, ordinal); $VALUES, values(), valueOf(String) exist; R8 builds $VALUES inline instead of calling $values(), verified by instruction scan of classes10.dex). Before fork 43b79e8 this shape rendered a parameterless constructor next to argument-carrying `new Syntax(\"SYNTAX_PROTO2\", ...)` calls, i.e. uncompilable Java, with values()/valueOf()/$VALUES suppressed. The pinned instance moved here from the saripaar enum on the retired xiaomi-router corpus.",
    },
    {
        "id": "region-reuse-bounded",
        "title": "shared-region reuse cannot explode the output",
        "kind": "class-shape",
        "status": "pass",
        "corpus": "framework",
        "class": "Landroid/view/View;",
        "max_stdout_bytes": 3000000,
        "max_ms": 20000,
        "note": "ground truth: measured. With unbounded region reuse, services.jar's DisplayPowerState$PhotonicModulator produced 2,268,053,229 bytes in 102.6 s (a shared region copied into a path that already contained a copy); that class retired with the services.jar corpus. The gate now pins the largest realistic framework class: android.view.View renders 1,911,526 bytes in ~0.2 s on 2026-06-21; a region-reuse regression that starts copying regions into copies blows straight past the 3 MB / 20 s budget.",
    },
    {
        "id": "ctor-invocation-pairing",
        "title": "new-instance + invoke-direct <init> stay one expression, even through a receiver copy",
        "kind": "class-shape",
        "status": "pass",
        "corpus": "wechat",
        "class": "Lcom/tencent/mm/chatting/basis/ChatListController;",
        "require_stdout_regex": [
            "(?s)MvvmList v([0-9_]+) = new com\\.tencent\\.mm\\.plugin\\.mvvmlist\\.MvvmList\\(v2, v3, v10, null, null, 24, null\\);.*?this\\.mvvmList = v\\1;",
        ],
        "forbid_stdout_regex": [
            "new com\\.tencent\\.mm\\.plugin\\.mvvmlist\\.MvvmList\\(\\)",
            "(?m)^\\s*new com\\.tencent\\.mm\\.plugin\\.mvvmlist\\.MvvmList\\(.*\\);\\s*$",
        ],
        "note": "ground truth: bytecode. In <init> the receiver of a seven-register invoke-direct/range <init> is a move-object copy of the new-instance register (found by instruction scan, classes.dex), so the instance stored in this.mvvmList is the one constructed with arguments. Until the vendored droidsaw-dex fix the look-ahead matched only the 35c `invoke-direct`, never `invoke-direct/range`, so the pair rendered as a bare `new MvvmList()` bound to the variable plus a discarded `new MvvmList(args)` statement -- invalid Java and an unconstructed object. The require pattern ties the constructed variable to the one stored, so a regression that only renames or reorders cannot pass. The previous pin (Lcom/xiaomi/push/r3; on the xiaomi-router APK) retired with that corpus; wechat alone has 10,329 classes with this shape.",
    },
    {
        "id": "intent-sanitizer-literals",
        "title": "a guard chain that shares one body keeps its literal and its call",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "settings",
        "class": "Landroidx/core/content/IntentSanitizer$Api31Impl;",
        "expect": {"missing_literals": 0, "empty_control": 0, "stub": 0, "allowed_signals": ["method-set"]},
        "require_stdout_regex": ["\\.accept\\(", "contains htmlText, textLinks or intent"],
        "note": "ground truth: reference + bytecode. The method-set signal is tolerated here and is a harness artefact: the reference inlines `new StringBuilder().append(..).toString()`, rasc uses `+` concatenation, so the library call names differ while the string literal -- the semantic anchor -- is present in both. The pinned androidx.core class is bundled by the settings APK (the fixture.apk corpus retired when the corpora moved to /tmp/rasc_corpus/); that build strips debug names, so the Consumer parameter renders as `v4` rather than `penalty` -- the pin is the accept call and the shared literal, not the name.",
    },
    {
        "id": "contracts-settings",
        "title": "CLI contracts hold on a device APK",
        "kind": "contracts",
        "status": "pass",
        "corpus": "settings",
        "note": "bench/contracts.sh: dotted == slashed descriptors, --threads determinism, -o equals stdout, SIGPIPE exits without panic, --debug only on stderr, missing class exits 1 with 'not found'.",
    },
    {
        "id": "contracts-wechat",
        "title": "CLI contracts hold on a second device APK",
        "kind": "contracts",
        "status": "pass",
        "corpus": "wechat",
    },
    {
        "id": "contracts-framework",
        "title": "CLI contracts hold on a system framework jar",
        "kind": "contracts",
        "status": "pass",
        "corpus": "framework",
    },
    {
        "id": "quality-settings",
        "title": "per-class quality over a device corpus stays within budget",
        "kind": "corpus-quality",
        "status": "pass",
        "corpus": "settings",
        "per_dex": 100,
        "max_flagged": 300,
        "note": "1300 sampled classes; measured 261 flagged (20.08%). Threshold has headroom; 0 errors is absolute.",
    },
    {
        "id": "quality-wechat",
        "title": "per-class quality over a second device corpus stays within budget",
        "kind": "corpus-quality",
        "status": "pass",
        "corpus": "wechat",
        "per_dex": 100,
        "max_flagged": 240,
        "note": "1600 sampled classes; measured 213 flagged (13.31%).",
    },
    {
        "id": "quality-framework",
        "title": "per-class quality over a system framework jar stays within budget",
        "kind": "corpus-quality",
        "status": "pass",
        "corpus": "framework",
        "per_dex": 1200,
        "max_flagged": 450,
        "note": "7,200 sampled classes (6 DEX x 1,200) on framework.jar; measured 355 flagged (4.93%) on 2026-06-21. Threshold has headroom; 0 errors is absolute.",
    },
    {
        "id": "pitfall-framework-exifinterface",
        "title": "framework pitfall: ExifInterface (heavy try/catch, big switch tables) stays within measured budget",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "framework",
        "class": "Landroid/media/ExifInterface;",
        "expect": {"missing_literals": 20, "missing_methods": 2, "max_empty_control": 2, "stub": 0},
        "note": "ground truth: reference. Measured 2026-06-21 on the pinned framework.jar: missing_literals=17, missing_methods=0, empty_control=1, stub=0; ceilings carry headroom so only a real regression trips.",
    },
    {
        "id": "pitfall-framework-sqliteconnection",
        "title": "framework pitfall: SQLiteConnection (dense guard chains, native state machine)",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "framework",
        "class": "Landroid/database/sqlite/SQLiteConnection;",
        "expect": {"missing_literals": 16, "missing_methods": 2, "max_empty_control": 1, "stub": 0},
        "note": "measured 2026-06-21: missing_literals=13, missing_methods=1, empty_control=0, stub=0.",
    },
    {
        "id": "pitfall-framework-colorspace-named",
        "title": "framework pitfall: ColorSpace$Named (enum class-init shape)",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "framework",
        "class": "Landroid/graphics/ColorSpace$Named;",
        "expect": {"missing_literals": 25, "missing_methods": 5, "max_empty_control": 1, "stub": 0},
        "note": "measured 2026-06-21: missing_literals=20, missing_methods=4, empty_control=0, stub=0.",
    },
    {
        "id": "pitfall-settings-durationkt",
        "title": "settings pitfall: kotlin.time.DurationKt (empty-control-flow signal present)",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "settings",
        "class": "Lkotlin/time/DurationKt;",
        "expect": {"missing_literals": 6, "missing_methods": 16, "max_empty_control": 5, "stub": 0},
        "note": "measured 2026-06-21: missing_literals=4, missing_methods=14, empty_control=4, stub=0. The empty-control-flow and method-set signals are reviewed known diffs; the ceilings turn them into a tripwire.",
    },
    {
        "id": "pitfall-settings-autofilltype",
        "title": "settings pitfall: compose autofill type table (literal-dense)",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "settings",
        "class": "Landroidx/compose/ui/autofill/AndroidAutofillType_androidKt;",
        "expect": {"missing_literals": 40, "missing_methods": 3, "max_empty_control": 1, "stub": 0},
        "note": "measured 2026-06-21: missing_literals=36, missing_methods=2, empty_control=0, stub=0.",
    },
    {
        "id": "pitfall-wechat-remittancedetailui",
        "title": "wechat pitfall: RemittanceDetailUI (obfuscated UI controller, empty-control-flow signal)",
        "kind": "class-parity",
        "status": "pass",
        "corpus": "wechat",
        "class": "Lcom/tencent/mm/plugin/remittance/ui/RemittanceDetailUI;",
        "expect": {"missing_literals": 6, "missing_methods": 6, "max_empty_control": 6, "stub": 0},
        "note": "measured 2026-06-21: missing_literals=4, missing_methods=5, empty_control=5, stub=0.",
    },
    {
        "id": "no-mocks-in-repo",
        "title": "no mocking framework or fake is used anywhere in the repo",
        "kind": "policy-no-mocks",
        "status": "pass",
        "forbidden_identifiers": ["unittest.mock", "from mock import", "import mock", "mock.patch", "MagicMock", "monkeypatch", "mockall", "mockito", "wiremock", "httpmock", "automock", "fake::", "class Fake", "def fake_"],
        "scan": ["src/**/*.rs", "bench/*.py", "bench/*.sh", "tests/**/*.rs", "tests/**/*.py"],
        "note": "executable form of the testing policy in AGENTS.md: every suite drives the real binary over real archives, so a mocking/faking import or helper anywhere is a policy violation, not a style choice. The needles are usage-shaped on purpose -- prose in the policy documents and in this runner may name them without violating anything.",
    },
    {
        "id": "cfg-parity",
        "title": "`rasc cfg` matches the reference control-flow graph",
        "kind": "not-implemented",
        "status": "not-implemented",
        "corpus": "settings",
        "acceptance_criteria": [
            "`rasc cfg <corpus> <dalvik-class> <method>` exits 0 for every method that has code, and 1 with a 'not found' message for a missing class/method",
            "block set and successor sets equal the reference's for the pinned methods (ground truth: reference on dev-0.1.0 droidasc/cli.py cfg, backed by bytecode branch offsets)",
            "--format dot output parses as a directed graph with one node per block; --format json is valid JSON with the same node/edge counts",
            "deterministic across --threads 1/4/8",
        ],
        "note": "criteria declared before implementation, per the testing policy. The reference implementation is droidasc/asc_core/analysis/cfg.py (447 lines) on dev-0.1.0.",
    },
    {
        "id": "analysis-commands-parity",
        "title": "`summary` / `aidl` / `receivers` on the rust branch match the reference",
        "kind": "not-implemented",
        "status": "not-implemented",
        "corpus": "framework",
        "acceptance_criteria": [
            "summary: byte-identical to the reference for the pinned class list, including the trailing blank line",
            "aidl: same interface set on framework.jar, same transaction-code values, byte-identical modulo line order",
            "receivers: same declared/dynamic/verified classification; the report matches the reference modulo ordering",
            "all three exit 0 and honour -o (file bytes == stdout bytes)",
        ],
        "note": "the implementations exist on wip/summary-aidl-receivers (583fcba) and are not merged into rust yet; the scenarios are declared first so the merge is judged against them rather than against 'tests pass'.",
    },
]
